# config.yaml

# URL de départ et paramètres de crawling
start_url: "https://votre-site-exemple.com/fr-ca/"
max_depth: 1
use_playwright: false
download_pdf: true
download_doc: true
download_image: false
download_other: false
max_urls: null  # Mettre un entier pour limiter le nombre d'URL ou null pour aucune limite

# Configuration du fournisseur LLM
llm:
  provider: "openai"  # Options: "openai", "anthropic", "mistral"
  api_keys:
    - "VOTRE_CLE_API_OPENAI"
    # - "VOTRE_CLE_API_ANTHROPIC"
    # - "VOTRE_CLE_API_MISTRAL"
  model: "gpt-4"  # Modèle spécifique du fournisseur
  system_prompt: "You are a helpful assistant."
  max_tokens_per_request: 2048
  temperature: 1
  top_p: 1

# Autres paramètres
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "logs/crawler.log"

# Extensions téléchargeables par catégorie
downloadable_extensions:
  PDF:
    - ".pdf"
  Image:
    - ".png"
    - ".jpg"
    - ".jpeg"
    - ".gif"
    - ".svg"
  Doc:
    - ".doc"
    - ".docx"
    - ".xls"
    - ".xlsx"
    - ".ppt"
    - ".pptx"
  Archive:
    - ".zip"
    - ".rar"
    - ".7z"
    - ".tar"
    - ".gz"
  Audio:
    - ".mp3"
    - ".wav"
    - ".ogg"
  Video:
    - ".mp4"
    - ".avi"
    - ".mov"
    - ".mkv"

# Mapping Content-Type / Extension
content_type_mapping:
  PDF:
    "application/pdf": ".pdf"
  Image:
    "image/jpeg": ".jpg"
    "image/png": ".png"
    "image/gif": ".gif"
    "image/svg+xml": ".svg"
  Doc:
    "application/msword": ".doc"
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ".docx"
    "application/vnd.ms-excel": ".xls"
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ".xlsx"
    "application/vnd.ms-powerpoint": ".ppt"
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": ".pptx"
  Archive:
    "application/zip": ".zip"
    "application/x-rar-compressed": ".rar"
    "application/x-7z-compressed": ".7z"
    "application/gzip": ".gz"
    "application/x-tar": ".tar"
  Audio:
    "audio/mpeg": ".mp3"
    "audio/wav": ".wav"
    "audio/ogg": ".ogg"
  Video:
    "video/mp4": ".mp4"
    "video/x-msvideo": ".avi"
    "video/quicktime": ".mov"
